//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneSubmissionSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentID { get; set; }
        public byte[] FileContent { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public int OwnerID { get; set; }
        public int TypeID { get; set; }
        public int Visibility { get; set; }
    
        public virtual DocType DocType { get; set; }
        public virtual User User { get; set; }
    }
}
